browser=chrome
base.url=https://www.saucedemo.com
retry.count=2

db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}


db.table.product=${DB_TABLE_PRODUCT}
db.table.classification=${DB_TABLE_CLASSIFICATION}
db.table.tax=${DB_TABLE_TAX}

db.col.tax.rate=${DB_COL_TAX_RATE}
db.col.product.id=${DB_COL_PRODUCT_ID}
db.col.classification.item.id=${DB_COL_CLASSIFICATION_ITEM_ID}
db.col.classification.code=${DB_COL_CLASSIFICATION_CODE}
db.col.tax.code=${DB_COL_TAX_CODE}
db.col.product.name=${DB_COL_PRODUCT_NAME}
