valid.username=${APP_USERNAME}
valid.password=${APP_PASSWORD}
firstname=Karthick
lastname=S
postcode=608001

#Items on the inventory page
item1=Sauce Labs Backpack
item2=Sauce Labs Bike
item3=Sauce Labs T-Shirt
item4=Sauce Labs Jacket
item5=Sauce Labs Onesie
item6=Test all


#Item prices (used for checkout price assertions)
backpack.price=29.99
